name: talkie
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publish

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  slide_to_act: ^2.0.2

  # State management and utilities
  get: ^4.7.2
  uuid: ^4.5.1
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  # Networking
  dio: ^5.9.0
  http: ^1.5.0

  # Media & assets
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  emoji_picker_flutter: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-ExtraBold.ttf
          weight: 800
